server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost/plazoleta_service
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
