server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost/plazoleta_service
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs